package medicalconsultation;

public enum dayMoment {
    BEFOREBREAKFAST, DURINGBREAKFAST, AFTERBREAKFAST, BEFORELUNCH,
    DURINGLUNCH, AFTERLUNCH, BEFOREDINNER, DURINGDINNER, AFTERDINNER,
    BEFOEMEALS, DURINGMEALS, AFTERMEALS;
}
